### ISSUE TITLE
Conflict with AzureRM.Security

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [azureandbeyond/AzurePS#2]
With AzureRM.Security coming out soon which has overlapping features with your JIT solution, are you planning to retire or continue this project?

https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Security/Commands.Security/help/AzureRM.Security.md

**Comment by TomJanetscheck** [comment]
@CHDAFNI-MSFT Thank you for asking. My code snippet for ASC JIT access was based on the unofficial https://github.com/Microsoft/Azure-Security-Center repo which has recently been closed.

I'm going to continue my AzurePS repo and change my snippets according to the newer modules.
Is there a .Net Core version of the AzureRM.Security module with az-commands such as Start-azJitNetworkAccessPolicy planned?

**Comment by CHDAFNI-MSFT** [comment]
‘Az’ is expected to be the same across .net and Core if that answers your question. Though it has not yet occurred, the “Az” version of AzureRM.Security is planned.

-------
(internal only) If I helped you, please take this 1-minute survey – https://aka.ms/chdafni-feedback

Chase Dafnis

Sr. Premier Field Engineer
US Public Sector
Microsoft Corporation

Office: 646.225.4724
Chase.Dafnis@microsoft.com<mailto:Chase.Dafnis@microsoft.com>

[Twitter]<https://twitter.com/Microsoft>    [Facebook] <https://www.facebook.com/Microsoft>     [Linkedin] <https://www.linkedin.com/company/microsoft>     [Youtube] <https://www.youtube.com/user/Microsoft>

[Microsoft Logo]

If you have any feedback about my work, please let either myself or my manager Arthur Dahl know at adahl@microsoft.com<mailto:adahl@microsoft.com>
